### ISSUE TITLE
Error: oversized record received with length 20527

### ISSUE THREAD

**Issue by mikolus** [mmatczuk/go-http-tunnel#102]
I'm trying to set up tunnel to my machine behind nat. Server that I'm using has external ip and domain name.
On the client I'm getting:

`level 0 msg dial failed network tcp addr 10.10.10.10:8000 err tls: oversized record received with length 20527`

Where 10.10.10.10 is the server's public ip, port 8000 on the server is open.
On the client, on request I'm getting:

`level 0 action round trip failed addr 95.150.97.128:58987 host 10.10.10.10:8000 url / err client not subscribed`

95.150.97.128 is the host I'm doing the request from.
My client's tunnel.yml:

```
server_addr: 10.10.10.10:8000
tunnels:
    djangoapp:
        proto: http
        addr: localhost:8000
        host: my-domain.co.uk
```
