### ISSUE TITLE
Add `host_header` modifier in tunnel configuration

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/go-http-tunnel#18]
> Rewrite the HTTP Host header to this value

**Comment by jonreeves** [comment]
Would be really useful because most of my projects that run Apache or Nginx are expecting to respond only to a particular Host request.

**Comment by findmyway** [comment]
Any update here?

I encounter a problem, not sure whether it is related to this thread.

My website is using the 4444 port on the server. By using Nginx, I proxy request to 80 port to my website.

In the meantime, I want to use go-http-tunnel to access my local machine, so I set the go-http-tunnel service listen port 5555(since 80 is already been used). And I write the nginx config as follows:

```
server{
    listen 80;
    server_name  tunnel.myownsite.com;

    access_log /var/log/nginx/tunnel_access.log;
    error_log /var/log/nginx/tunnel_error.log;

    location / {
        proxy_pass http://localhost:5555/;
        proxy_set_header Host $http_host;
    }
}

```

The client config is as follows:

```
server_addr: 52.183.47.200:4567
insecure_skip_verify: true
tunnels:
  webui:
    proto: http
    addr: localhost:8080
    host: localhost
```

On my server, I can use `wget localhost:5555` to access the local machine. Request of **tunnel.myownsite.com** said 

```
client not subscribed
```
Thank you very much!

**Comment by hexenskull** [comment]
@findmyway hey, I don't know if this is still useful for you but I managed to populate my HTTP website that is running on my localhost:5001 to my remote AWS instance 0.0.0.0:5002
with this tunnel.yml :

```yml
    server_addr: MY_AWS_PUBLIC_IP:5223
    tunnels:
      my_website:
        proto: tcp
        addr: 127.0.0.1:5001
        remote_addr: 0.0.0.0:80
```

and I can access my website that is running on my pc at home from: MY_AWS_PUBLIC_IP

you can add specific dns to your IP from services like [godaddy.com](https://godaddy.com/)
