### ISSUE TITLE
panic: Empty localAddrMap

### ISSUE THREAD

**Issue by bgaillard** [mmatczuk/go-http-tunnel#26]
Hi, I encounter a problem while starting `tunnel.exe` under Windows.

My configuration is the following (I've hidden the IP address and real domain name for security reasons).

```
server_addr: 1.2.3.4:443
insecure_skip_verify: true
tunnels:
  webui:
    proto: http
    addr: localhost:8080
    host: myserver.mydomain.com
```

When I execute the client command I encounter the following error.

```
.\tunnel.exe -config .\tunnel.yml start webui
2017/07/12 19:40:18 config server_addr: 1.2.3.4:443
insecure_skip_verify: true
tls_crt: client.crt
tls_key: client.key
backoff:
  interval: 500ms
  multiplier: 1.5
  max_interval: 1m0s
  max_time: 15m0s
tunnels:
  webui:
    proto: http
    addr: http://localhost:8080
    host: myserver.mydomain.com

panic: Empty localAddrMap

goroutine 1 [running]:
github.com/mmatczuk/go-http-tunnel.NewMultiTCPProxy(0xc042163aa0, 0x8c7da0, 0xc042164100, 0x2)
        /home/mmatczuk/projects/tunnel/src/github.com/mmatczuk/go-http-tunnel/tcpproxy.go:48 +0x168
main.proxy(0xc04206da40, 0x8c8e60, 0xc04211d500, 0x2)
        /home/mmatczuk/projects/tunnel/src/github.com/mmatczuk/go-http-tunnel/cmd/tunnel/tunnel.go:164 +0x60c
main.main()
        /home/mmatczuk/projects/tunnel/src/github.com/mmatczuk/go-http-tunnel/cmd/tunnel/tunnel.go:104 +0x79a
```

Do you know what's the problem here ? 

Thanks
