### ISSUE TITLE
 yaml: line 1: did not find expected key

### ISSUE THREAD

**Issue by xtrsyz** [mmatczuk/go-http-tunnel#51]
configuration error: failed to parse file ".tunnel/tunnel.yml": yaml: line 1: did not find expected key
with config
server_addr: "185.2.2.137:4443"
    insecure_skip_verify: true
    tunnels: ...

./tunnel -version
3d03804

**Comment by mmatczuk** [comment]
I think your file is broken. It should be like.

```yaml
server_addr: 185.2.2.137:4443
insecure_skip_verify: true
tunnels:
  webui:
    proto: http
    addr: localhost:8080
    auth: user:password
    host: webui.my-tunnel-host.com
  ssh:
    proto: tcp
    addr: 192.168.0.5:22
    remote_addr: 0.0.0.0:22
```
