### ISSUE TITLE
On reload redirects to the local address

### ISSUE THREAD

**Issue by applegrew** [mmatczuk/go-http-tunnel#84]
I am facing a weird issue. My tunnel.yaml file is as below :-

```
server_addr: example.com:5223
tunnels:
      now:
        proto: http
        addr: http://127.0.0.1:8080
        host: me.example.com
```

On server side `-httpAddr` is set to `:8000`. When I access the site from the browsers as `http://me.example.com:8000` it works fine. However, when I reload the site I get a 302 from the site and I am redirected to `http://127.0.0.1:8080`. The actual site does not seem to issue the 302. It seems like go-http-tunnel is issuing that for some reason. If I goto some other url and come back to the same url I do not get the 302; it is only when I hit the same url twice consecutively I get the 302. If I change the `addr:` to say `https://google.com` then I do not see this issue.
